title: "🤔 Molestaciones Matemáticas"
subtitle: "Math Annoyancements"
email:
description: >-
  Cosas interesantes para mí

github_username: lucianoprofecbc-creator
locale: es-AR
minimal_mistakes_skin: default
logo: "/assets/images/thinking.png"
masthead_title: "Molestaciones Matemáticas"
search: true

head_scripts:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: "mmistakes/minimal-mistakes"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Luciano Alejo Perez"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Estuve pensando...🤔"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
